name: .NET

on:
  push:
    branches: [ master ]
    paths-ignore: 
    - .github/**
    - .gitignore
    - README.md
    - LICENSE
    - docker-compose.yml
    - Dockerfile
  workflow_dispatch:
  
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core on Windows
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build with dotNet
      run: dotnet build --configuration Release

